# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 207aade040390c87f9678ef35971010d8066a14b0914a6a8153e1e7a20e6b47be28b92ffa37840d4e4227c72388cae2963c355dddc2973670d8ae064974ae10c

test:
  secret_key_base: 055b88f6b7d654d1f82077f6a542e2f0f0f3f4bbf44759def418448950797d4dfbdae4e21bf88f42596f9a8113de19c831bf7f926a7c83f02d558e2d50613e5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
